version: "3.7"

services:
  app1:
    image: simple-app
    container_name: counter1
    ports:
      - "3000:8080"
    command: sh -c "yarn install && yarn run dev"
    working_dir: /spring-boot-simple
    
  app2:
    image: simple-app
    container_name: counter2
    ports:
      - "3001:8080"
    command: sh -c "yarn install && yarn run dev"
    working_dir: /spring-boot-simple